<%
		
'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
dim conn
Set conn = Server.CreateObject("ADODB.Connection")
conn.Open("DRIVER={MySQL ODBC 5.1 Driver};SERVER=mysql28.fidigital.com.br;PORT=3306;DATABASE=newdot27;USER=newdot27;PASSWORD=a2x3z4;OPTION=3;")

'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
%>